import { de } from 'date-fns/locale'

export const siteConfig = {
	metaData: {
		title: 'Sammi | Dasturlash kurslari',
		description:
			"Sammi dasturlash kurslari - dasturlashni o'rganish uchun eng yaxshi manba. Bizning kurslarimiz bilan siz dasturlashni o'rganishingiz mumkin.",
		author: 'Dilshodbek Gulomov',
		keywords: [
			'dasturlash',
			'kurslar',
			'Sammi',
			'JavaScript',
			'Python',
			'HTML',
			'CSS',
			'React',
			'Node.js',
			'Express.js',
			'MongoDB',
			'Django',
			'Flask',
			'Vue.js',
			'Angular',
			'TypeScript',
			'Java',
			'C++',
			'C#',
			'PHP',
			'Ruby on Rails',
			'Sass',
			'Tailwind CSS',
			'Bootstrap',
			'jQuery',
			'Git',
			'GitHub',
			'API',
			'restful API',
			'rest API',
			'restful web services',
			'restful web service tutorial',
			'restful web service example',
		],
	},
	baseURL: 'https://sammi.ac',
	logo: '/logo.svg',
	logoText: 'Sammi',
	favicon: '/favicon.ico',
	copyright: 'All rights reserved.',
}
